-- This script was generated by a beta version of the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE public.users
(
    id integer,
    email character(100) NOT NULL,
    sifre character(40) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE public.system_personnel
(
    personel_id integer,
    ad character(60) NOT NULL,
    soyad character(100) NOT NULL,
    PRIMARY KEY (personel_id)
);

CREATE TABLE public.condidates
(
    aday_id integer,
    ad character(70) NOT NULL,
    soyad character(100) NOT NULL,
    "tc_no" character(11) NOT NULL,
    dogum_tarih date NOT NULL,
    PRIMARY KEY (aday_id)
);

CREATE TABLE public.employers
(
    isveren_id integer,
    sirket_adi character(200) NOT NULL,
    website character(150) NOT NULL,
    telefon character(25) NOT NULL,
    PRIMARY KEY (isveren_id)
);

CREATE TABLE public.job_positions
(
    id integer,
    pozisyon_adi character(100) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE public.mernis_activate
(
    id integer,
    onay_durumu boolean NOT NULL,
    condidates_id integer NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE public.eposta_activate
(
    id integer,
    onay_durumu boolean NOT NULL,
    condidates_id integer NOT NULL,
    employers_id integer NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE public.personel_activate_for_employers
(
    id integer,
    onay_durumu boolean NOT NULL,
    personel_id integer NOT NULL,
    PRIMARY KEY (id)
);

ALTER TABLE public.users
    ADD FOREIGN KEY (id)
    REFERENCES public.system_personnel (personel_id)
    NOT VALID;


ALTER TABLE public.users
    ADD FOREIGN KEY (id)
    REFERENCES public.condidates (aday_id)
    NOT VALID;


ALTER TABLE public.users
    ADD FOREIGN KEY (id)
    REFERENCES public.employers (isveren_id)
    NOT VALID;


ALTER TABLE public.mernis_activate
    ADD FOREIGN KEY (condidates_id)
    REFERENCES public.condidates (aday_id)
    NOT VALID;


ALTER TABLE public.eposta_activate
    ADD FOREIGN KEY (condidates_id)
    REFERENCES public.condidates (aday_id)
    NOT VALID;


ALTER TABLE public.eposta_activate
    ADD FOREIGN KEY (employers_id)
    REFERENCES public.employers (isveren_id)
    NOT VALID;


ALTER TABLE public.personel_activate_for_employers
    ADD FOREIGN KEY (personel_id)
    REFERENCES public.system_personnel (personel_id)
    NOT VALID;

END;

--insert into condidates(aday_id,ad,soyad,tc_no,dogum_tarih)
--values(1,'Mert','Oğuzhan','12345678911','2021-05-10');

--select * from condidates

--insert into mernis_activate(id,onay_durumu,condidates_id)
--values(1,'t',1);

--select * from mernis_activate

